import json
import os
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

DATABASE = "provenance_guard.db"


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def get_db():
    conn = sqlite3.connect(DATABASE)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS content_decisions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            content_id TEXT UNIQUE NOT NULL,
            creator_id TEXT NOT NULL,
            text TEXT NOT NULL,
            attribution TEXT NOT NULL,
            confidence REAL NOT NULL,
            label TEXT NOT NULL,
            status TEXT NOT NULL,
            llm_score REAL NOT NULL,
            heuristic_score REAL NOT NULL,
            llm_reasoning TEXT,
            heuristic_reasoning TEXT,
            appeal_reasoning TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            event_type TEXT NOT NULL,
            content_id TEXT NOT NULL,
            creator_id TEXT,
            attribution TEXT,
            confidence REAL,
            llm_score REAL,
            heuristic_score REAL,
            label TEXT,
            status TEXT,
            appeal_reasoning TEXT,
            details TEXT
        )
        """
    )
    conn.commit()
    conn.close()


def clamp(value, low=0.0, high=1.0):
    return max(low, min(high, value))


def classify_score(score):
    if score >= 0.75:
        return "likely_ai"
    if score >= 0.45:
        return "uncertain"
    return "likely_human"


def transparency_label(attribution):
    if attribution == "likely_ai":
        return (
            "Provenance Guard notice: This post appears likely to have been generated by AI. "
            "This label is based on writing-pattern signals and should not be treated as absolute proof."
        )
    if attribution == "likely_human":
        return (
            "Provenance Guard notice: This post appears likely to be human-written based on its "
            "writing patterns. This label is an estimate, not a guarantee."
        )
    return (
        "Provenance Guard notice: This post has mixed writing-pattern signals, so its origin is "
        "uncertain. It may be human-written, AI-assisted, or edited from multiple sources."
    )


def stylistic_heuristic_signal(text):
    words = re.findall(r"\b[\w']+\b", text.lower())
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    word_count = len(words)

    score = 0.50
    reasons = []

    ai_phrases = [
        "it is important to note",
        "transformative",
        "paradigm shift",
        "stakeholders",
        "ethical implications",
        "responsible deployment",
        "various sectors",
        "furthermore",
        "additionally",
        "in conclusion",
        "essential",
        "numerous",
    ]

    personal_markers = [
        "i",
        "me",
        "my",
        "we",
        "honestly",
        "kinda",
        "sort of",
        "my friend",
        "downtown",
        "i was",
        "i've",
        "won't",
        "can't",
    ]

    ai_hits = sum(1 for phrase in ai_phrases if phrase in text.lower())
    personal_hits = sum(1 for marker in personal_markers if marker in text.lower())

    if ai_hits:
        score += min(0.28, ai_hits * 0.055)
        reasons.append(f"found {ai_hits} formal or AI-like phrases")

    if personal_hits:
        score -= min(0.30, personal_hits * 0.05)
        reasons.append(f"found {personal_hits} personal or informal markers")

    if len(sentences) >= 3:
        sentence_lengths = [len(re.findall(r"\b[\w']+\b", s)) for s in sentences]
        avg_len = sum(sentence_lengths) / len(sentence_lengths)
        variance = sum((x - avg_len) ** 2 for x in sentence_lengths) / len(sentence_lengths)

        if variance < 18 and avg_len >= 12:
            score += 0.12
            reasons.append("sentence lengths are fairly uniform")
        elif variance > 55:
            score -= 0.08
            reasons.append("sentence lengths vary in a more human-like way")

    if word_count < 35:
        score = (score + 0.50) / 2
        reasons.append("short text limits confidence")

    if not reasons:
        reasons.append("no strong heuristic pattern detected")

    return {
        "score": round(clamp(score), 3),
        "reasoning": "; ".join(reasons),
    }


def fallback_llm_signal(text):
    heuristic = stylistic_heuristic_signal(text)
    adjusted = (heuristic["score"] * 0.85) + 0.075
    return {
        "score": round(clamp(adjusted), 3),
        "reasoning": "Groq was unavailable, so the system used a fallback semantic estimate based on the same text-pattern evidence.",
    }


def llm_signal(text):
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key or api_key == "your_key_here":
        return fallback_llm_signal(text)

    prompt = f"""
You are part of Provenance Guard, a cautious AI provenance system.

Score whether this submitted text appears AI-generated or human-written.

Return ONLY valid JSON in this exact shape:
{{
  "score": 0.0,
  "reasoning": "brief reason"
}}

Scoring:
0.00 = very likely human-written
0.50 = uncertain or mixed
1.00 = very likely AI-generated

Be careful with false positives. Polished human writing is possible.

Submitted text:
{text}
"""

    try:
        client = Groq(api_key=api_key)
        response = client.chat.completions.create(
            model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        parsed = json.loads(match.group(0) if match else raw)
        return {
            "score": round(clamp(float(parsed.get("score", 0.5))), 3),
            "reasoning": str(parsed.get("reasoning", "LLM returned no reasoning.")),
        }
    except Exception as exc:
        fallback = fallback_llm_signal(text)
        fallback["reasoning"] = f"Groq signal failed, fallback used. Error summary: {type(exc).__name__}."
        return fallback


def combined_confidence(llm_score, heuristic_score):
    return round(clamp((llm_score * 0.60) + (heuristic_score * 0.40)), 3)


def write_audit_log(
    event_type,
    content_id,
    creator_id=None,
    attribution=None,
    confidence=None,
    llm_score=None,
    heuristic_score=None,
    label=None,
    status=None,
    appeal_reasoning=None,
    details=None,
):
    conn = get_db()
    conn.execute(
        """
        INSERT INTO audit_log (
            timestamp, event_type, content_id, creator_id, attribution, confidence,
            llm_score, heuristic_score, label, status, appeal_reasoning, details
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            now_iso(),
            event_type,
            content_id,
            creator_id,
            attribution,
            confidence,
            llm_score,
            heuristic_score,
            label,
            status,
            appeal_reasoning,
            json.dumps(details or {}),
        ),
    )
    conn.commit()
    conn.close()


@app.get("/")
def home():
    return jsonify(
        {
            "service": "Provenance Guard",
            "endpoints": ["POST /submit", "POST /appeal", "GET /log"],
        }
    )


@app.post("/submit")
@limiter.limit("10 per minute")
def submit_content():
    data = request.get_json(silent=True) or {}
    text = str(data.get("text", "")).strip()
    creator_id = str(data.get("creator_id", "")).strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400

    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())[:8]

    llm_result = llm_signal(text)
    heuristic_result = stylistic_heuristic_signal(text)

    llm_score = llm_result["score"]
    heuristic_score = heuristic_result["score"]
    confidence = combined_confidence(llm_score, heuristic_score)
    attribution = classify_score(confidence)
    label = transparency_label(attribution)
    status = "classified"
    timestamp = now_iso()

    conn = get_db()
    conn.execute(
        """
        INSERT INTO content_decisions (
            content_id, creator_id, text, attribution, confidence, label, status,
            llm_score, heuristic_score, llm_reasoning, heuristic_reasoning,
            created_at, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            content_id,
            creator_id,
            text,
            attribution,
            confidence,
            label,
            status,
            llm_score,
            heuristic_score,
            llm_result["reasoning"],
            heuristic_result["reasoning"],
            timestamp,
            timestamp,
        ),
    )
    conn.commit()
    conn.close()

    write_audit_log(
        event_type="submission",
        content_id=content_id,
        creator_id=creator_id,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        heuristic_score=heuristic_score,
        label=label,
        status=status,
        details={
            "text_preview": text[:120],
            "llm_reasoning": llm_result["reasoning"],
            "heuristic_reasoning": heuristic_result["reasoning"],
        },
    )

    return jsonify(
        {
            "content_id": content_id,
            "creator_id": creator_id,
            "attribution": attribution,
            "confidence": confidence,
            "label": label,
            "status": status,
            "signals": {
                "llm_score": llm_score,
                "heuristic_score": heuristic_score,
                "llm_reasoning": llm_result["reasoning"],
                "heuristic_reasoning": heuristic_result["reasoning"],
            },
        }
    )


@app.post("/appeal")
def appeal_content():
    data = request.get_json(silent=True) or {}
    content_id = str(data.get("content_id", "")).strip()
    creator_reasoning = str(data.get("creator_reasoning", "")).strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400

    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    conn = get_db()
    row = conn.execute(
        "SELECT * FROM content_decisions WHERE content_id = ?",
        (content_id,),
    ).fetchone()

    if row is None:
        conn.close()
        return jsonify({"error": "Unknown content_id"}), 404

    conn.execute(
        """
        UPDATE content_decisions
        SET status = ?, appeal_reasoning = ?, updated_at = ?
        WHERE content_id = ?
        """,
        ("under_review", creator_reasoning, now_iso(), content_id),
    )
    conn.commit()
    conn.close()

    write_audit_log(
        event_type="appeal",
        content_id=content_id,
        creator_id=row["creator_id"],
        attribution=row["attribution"],
        confidence=row["confidence"],
        llm_score=row["llm_score"],
        heuristic_score=row["heuristic_score"],
        label=row["label"],
        status="under_review",
        appeal_reasoning=creator_reasoning,
        details={
            "original_status": row["status"],
            "original_attribution": row["attribution"],
        },
    )

    return jsonify(
        {
            "content_id": content_id,
            "status": "under_review",
            "appeal_received": True,
            "creator_reasoning": creator_reasoning,
            "original_attribution": row["attribution"],
        }
    )


@app.get("/log")
def get_log():
    limit = request.args.get("limit", default=10, type=int)
    limit = min(max(limit, 1), 50)

    conn = get_db()
    rows = conn.execute(
        """
        SELECT timestamp, event_type, content_id, creator_id, attribution,
               confidence, llm_score, heuristic_score, label, status,
               appeal_reasoning, details
        FROM audit_log
        ORDER BY id DESC
        LIMIT ?
        """,
        (limit,),
    ).fetchall()
    conn.close()

    entries = []
    for row in rows:
        entry = dict(row)
        try:
            entry["details"] = json.loads(entry["details"] or "{}")
        except json.JSONDecodeError:
            entry["details"] = {}
        entries.append(entry)

    return jsonify({"count": len(entries), "entries": entries})


if __name__ == "__main__":
    init_db()
    app.run(debug=True, port=5000)
